# Site settings
title: Community-run CMX Slack
email: alexandra.anna.bowen@gmail.com
url: https://cmxslack.github.io
description: "We Are Community Managers and Developer Evangelists- and So Can You! exists to facilitate sharing information, resources and encouragement among the community."

# Contact form: comment the line below if you want to stick with the default PHP contact form
# contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings -- these are titles of the section
footer:
  copyright: We Are Community Managers and Developer Evangelists
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: http://communitymanagerscmx.slack.com
  - title: github
    url: http://github.com/cmxslack/
  - title: twitter
    url: https://twitter.com/cmx



# CodeOfConduct
CodeOfConduct: 'Read our Community-Run Slack <a href="https://github.com/cmxslack/getting-started/blob/master/CodeOfConduct.md">Code Of Conduct.</a>'

# Build settings
markdown: kramdown
permalink: pretty
